
import type { Product } from './types';
import { ProductCategory } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Kienyeji Eggs',
    description: 'Fresh, organic kienyeji eggs from free-range chicken in the Rift Valley. Perfect for a healthy breakfast.',
    price: 300, // Bei kwa KSh
    quantity: 50, // Idadi
    category: ProductCategory.Poultry,
    imageUrl: 'https://picsum.photos/seed/eggs/400/300',
    location: 'Nakuru, Rift Valley',
    tags: ['organic', 'fresh', 'free-range'],
    sellerId: 'seller-1',
    sellerName: 'Wanjiku Farms',
    sellerRating: 4.8,
  },
  {
    id: 'prod-2',
    name: 'Maasai Beaded Necklace',
    description: 'Handcrafted traditional Maasai necklace with vibrant beads. A beautiful piece of Kenyan culture.',
    price: 1500,
    quantity: 15,
    category: ProductCategory.Jewellery,
    imageUrl: 'https://picsum.photos/seed/maasai/400/300',
    location: 'Kajiado, Rift Valley',
    tags: ['handmade', 'cultural', 'beads'],
    sellerId: 'seller-2',
    sellerName: 'Naserian Crafts',
    sellerRating: 4.9,
  },
  {
    id: 'prod-3',
    name: 'Fresh Sukuma Wiki',
    description: 'A large bunch of freshly harvested sukuma wiki (collard greens). Staple for any Kenyan meal.',
    price: 50,
    quantity: 100,
    category: ProductCategory.Food,
    imageUrl: 'https://picsum.photos/seed/sukuma/400/300',
    location: 'Limuru, Central',
    tags: ['vegetable', 'fresh', 'farm-direct'],
    sellerId: 'seller-1',
    sellerName: 'Wanjiku Farms',
    sellerRating: 4.8,
  },
  {
    id: 'prod-4',
    name: 'Sisal Kiondo Bag',
    description: 'Durable and stylish handwoven sisal bag (kiondo). Perfect for shopping or as a fashion accessory.',
    price: 1200,
    quantity: 25,
    category: ProductCategory.Accessories,
    imageUrl: 'https://picsum.photos/seed/kiondo/400/300',
    location: 'Machakos, Eastern',
    tags: ['handwoven', 'sisal', 'eco-friendly'],
    sellerId: 'seller-3',
    sellerName: 'Mama Mboga Weavers',
    sellerRating: 4.7,
  },
  {
    id: 'prod-5',
    name: 'Kienyeji Chicken (Live)',
    description: 'Healthy and active live kienyeji chicken. Raised on natural feeds.',
    price: 800,
    quantity: 30,
    category: ProductCategory.Poultry,
    imageUrl: 'https://picsum.photos/seed/chicken/400/300',
    location: 'Kisumu, Nyanza',
    tags: ['live', 'free-range', 'kienyeji'],
    sellerId: 'seller-4',
    sellerName: 'Onyango Poultry',
    sellerRating: 4.6,
  },
  {
    id: 'prod-6',
    name: 'Sun-Dried Maize',
    description: '2kg bag of high-quality, sun-dried maize, ready for milling into ugali flour.',
    price: 250,
    quantity: 80,
    category: ProductCategory.Food,
    imageUrl: 'https://picsum.photos/seed/maize/400/300',
    location: 'Eldoret, Rift Valley',
    tags: ['cereal', 'gmo-free', 'ugali'],
    sellerId: 'seller-5',
    sellerName: 'Chebet Grains',
    sellerRating: 4.8,
  },
  {
    id: 'prod-7',
    name: 'Young Goat (Mbuzi)',
    description: 'A healthy young goat, ideal for breeding or for an event. Raised in open pastures.',
    price: 4500,
    quantity: 10,
    category: ProductCategory.Livestock,
    imageUrl: 'https://picsum.photos/seed/goat/400/300',
    location: 'Garissa, North Eastern',
    tags: ['livestock', 'mbuzi', 'nyama-choma'],
    sellerId: 'seller-6',
    sellerName: 'Ali\'s Pastoralists',
    sellerRating: 4.5,
  },
];
